# Generated by Django 2.1.5 on 2019-02-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
