# Generated by Django 5.2.4 on 2025-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190206_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
